### ISSUE TITLE
BP参考资源

### ISSUE THREAD

**Issue by alissli** [alissli/MuLanStar#1]
- [老树新芽](https://github.com/AIWriter/TeamLeader.Writer/issues/9)
- [普拉提](https://github.com/Lauren83/writer004-final-BP-project/issues/1)
- [童行书院](https://github.com/gabriel-guobin/ChildAcademy)
- [月亮猫](https://github.com/WangJane1030/Shescoding/issues)
- [开智部落](https://github.com/linhaotao/writer004bp-openmindworld/issues)

**Comment by alissli** [comment]
- [BP团队协作](https://github.com/AIWriter/Writer005/wiki/HbFinalProjectCollaborate#如何组建团队，开启共创？)

**Comment by alissli** [comment]
### 素材学习

- 挑选优秀作业，分析其故事模型，组块
- 比较同一优秀作业的不同版本，找出修改点
- 迭代自己的版本

**Comment by alissli** [comment]
### 普拉提

- 故事
  - 事件1: hold住先生腰疼（寻找多种办法，无效果）
  - 事件2: hold住先生遇到普拉提Robert（了解普拉提），练习普拉提
  - 事件3：hold住先生身体状态改善，改变了生活方式

- 组块
  - hold住先生是一位白领，工作压力大，身体常常出问题，找了很多办法，都没有效果
  - hold住先生想要解决问题，遇到了Robert，了解了普拉提，可以帮助自己更好的控制身体
  - hold住先生开始练习普拉提，3个月后，身体好多了，工作也更顺心了

**Comment by alissli** [comment]
### 开智部落

- 最小故事
  - 事件1: 女程序员李思齐想当作家
  - 事件2: 朋友推荐了开智app
  - 事件3: 李思齐没有当上作家，但帮其他人实现了作家梦。

- 组块
  - 女程序媛李思齐想当作家，白天忙碌工作，晚上写作，很孤独
  - 女程序媛遇到了开智部落，用作品和伙伴交流，参与了「写匠」项目，认识了伙伴陈仁远
  - 女程序猿没有变成作家，但是「写匠」帮其他人写出很好的作品，并且收获了爱情

- 优点
  - 利用了记忆生存优势效应，「星空」，「火把」，「跳动的火苗」

**Comment by alissli** [comment]
## 历史上的女性

- [第一位获诺贝尔文学奖的女性](https://baike.baidu.com/item/塞尔玛·拉格洛夫/9452606?fr=aladdin&fromid=2610204&fromtitle=西尔玛·拉格洛夫)
- [中国历史上著名女作家](https://zhidao.baidu.com/question/180198899743975724.html)
- [陈衡哲](http://ah.people.com.cn/n2/2016/0222/c358327-27783278.html)

**Comment by hellomandy** [comment]
[如何看待Google工程师发长文称「女子编程不如男」？](http://mp.weixin.qq.com/s?__biz=MzIzNzcwMjI5OQ==&mid=2247484196&idx=1&sn=f309774883c61d58c0dc516cb8d1b917&chksm=e8c5ded0dfb257c656148ad0701fe9cd78d3c7ff6d405b0c047799345e2c3b6ccf65305ada0f&mpshare=1&scene=1&srcid=1211uQ5oGkojdcyO9db9Jsuj#rd)
[问答四则：彭宇案、波多黎各、进化论与哲学、爸爸疼女儿](http://mp.weixin.qq.com/s?__biz=MzIzNzcwMjI5OQ==&mid=2247484037&idx=1&sn=a95362191a918a223a6c6114fd514785&chksm=e8c5df71dfb256678de6901b1866454a2f88a1fafaddbf58d8c8d258009b82828fc49722bdbd&mpshare=1&scene=1&srcid=0615KtG3L4o1M4UOsGqpP7rY#rd)
[TED演讲：男女平等有益于每一个人，包括男人](https://www.ted.com/talks/michael_kimmel_why_gender_equality_is_good_for_everyone_men_included/transcript?language=zh-cn) 分享者提出：特权对拥有者而言是无形的，拥有的人感觉不到它。
[TED演讲：电影中的男子气概](https://www.ted.com/talks/colin_stokes_how_movies_teach_manhood?language=zh-cn)
[TED演讲：男女真的平等吗](http://open.163.com/movie/2016/8/G/6/MBSHSE0LB_MBSHTAJG6.html)
[TED演讲：12亿条推文推动男女平等](http://open.163.com/movie/2016/2/5/5/MBG2E3JSD_MBG2EA255.html)


[TED演讲：为什么女性领导那么少](http://open.163.com/movie/2011/7/5/A/M77989MRB_M779G7B5A.html)来自《lean in》分享者 Sheryl Sandberg的观点和“拥有特权的人感受不到特权”这一观点不谋而合

**Comment by alissli** [comment]
### 老阳ch07答疑（重点回看BP答疑部分）

- 如何讲故事
  - 利用人性填空，构造最小故事
  - 采用树型结构，由最小故事生成简单故事
  - 由简单故事生成复杂故事
  - **关键是在意向层次上展开故事**，比如张爱玲《红玫瑰与白玫瑰》，白玫瑰知道振保不爱她，振保知道自己不爱白玫瑰，也知道白玫瑰知道自己不爱她。但不知道白玫瑰给他带绿帽子，而且是他看不上的人。
  

- 故事与文采
  - 文采的时空变形指的是文字层面的变形
  - 故事中的时空变形指的是日常生活中的内核包装、变得荒谬或者唯美。比如纳博科夫的《洛丽塔》是基于一则新闻报道，又比如讲一个「幼儿园」的产品，孩子现在在「红黄蓝」（我当时想起今年上海一号线故障时，有个编辑写了一个气球挽留爸爸的故事）。

- 故事的逆转技巧
  - 使用空间的场景和词汇
  - 使用产品和服务提供逆转
  - 如果是人，在故事的叙事结构中添加空间因素，比如一个「以前爱，现在不爱」的故事，韩剧的典型套路是男女主人公从小青梅竹马（是**邻居**），后来女主人公进入**大公司**工作，认识了霸道总裁，就不爱男主人公了。

**Comment by alissli** [comment]
- [十二教练推荐图标库](https://www.flaticon.com/)
- [做 BP 如何安排进度？双钻设计模型来帮你 ](https://github.com/AIWriter/Writer005/issues/253)

**Comment by hellomandy** [comment]
TED演讲：12亿条推文推动男女平等中提到的网站[hefrorshe](http://www.heforshe.org/en/our-mission)
我认为这就是国际版的木兰星

**Comment by alissli** [comment]
- [20170420 李嘉文反馈](https://github.com/linhaotao/writer004bp-openmindworld/issues/3)
- [以每页每帧为基本单位表达](https://github.com/linhaotao/writer004bp-openmindworld/issues/6)

**Comment by alissli** [comment]
- [Why women earn less: Just two factors explain post-PhD pay gap](http://www.nature.com/news/why-women-earn-less-just-two-factors-explain-post-phd-pay-gap-1.19950)
- [男人能是女权主义者吗？](https://www.douban.com/note/245923875/)
- [长平：作为女权主义者的我](https://www.douban.com/note/88200339/)
- [Feminism](https://www.ted.com/talks?topics%5B%5D=feminism)
- [长平谈男性女权者：不能假装自己不是墙里那块砖](https://weibo.com/p/1001603902249448424207)
- [一位成功女企业家Dame Stephanie Shirley的传奇故事](https://www.ted.com/talks/dame_stephanie_shirley_why_do_ambitious_women_have_flat_heads?language=zh-cn)

**Comment by alissli** [comment]
- [女生就业，为啥这么难？](https://weibo.com/ttarticle/p/show?id=2309403927841124256328)
- [怎样做一名女权主义者](https://weibo.com/p/1001603836190460611084)
- [辩护者：一条性别歧视微博的四年论争](https://weibo.com/ttarticle/p/show?id=2309404171454185877274#_0)
- [家族企业中性别歧视减弱](http://www.ftchinese.com/story/001075592?full=y&ccode=2G172001)
- [漫画：你也在受到性别歧视的伤害](https://mp.weixin.qq.com/s?__biz=MzA3OTg4MDUyNw==&mid=201349231&idx=1&sn=805f6f1fcc4be37ea9865080c37c6ab1&scene=2&from=timeline&isappinstalled=0#rd)
- [哈佛大学：寓性别教育于日常](http://www.infzm.com/content/131531)
- [中国职场距离性别平等还有多远？](http://www.ftchinese.com/story/001075373?page=2)

**Comment by alissli** [comment]
- [加拿大女权主义国际援助政策](http://www.international.gc.ca/gac-amc/campaign-campagne/iap-pai/index.aspx?lang=eng)
- [盖茨基金会](https://www.gatesfoundation.org/yearinreview/2017/zh/review/gender-equality)

**Comment by alissli** [comment]
- [women in science](https://www.britannica.com/topic/Women-in-Science-2100321#ref1115764)

**Comment by alissli** [comment]
- [You can fly](http://baidu.iqiyi.com/watch/0408578416636971514.html?page=videoMultiNeed)
- [一本法国男人写给老公的书](http://www.ngocn.net/news/2017-11-22-f95cc318e089cf9f.html)
- [淡豹：为什么总是女性难以平衡职业和家庭？](http://www.ngocn.net/news/2017-11-21-5d03961a1b51e551.html)
- [真的有“剩男剩女”吗？看看数据怎么说](http://www.ngocn.net/news/2017-11-14-5c70bbe9f1d29ba3.html)
- [飞向宇宙，女性可以引领无限可能！](http://www.ngocn.net/news/2017-11-08-0ed12de766dc2905.html)
- [最新性别差距报告出炉！中国跌出两位数，离性别平等还很远](http://www.ngocn.net/news/2017-11-03-0f860e92d06bfabc.html)
- [语言与女性地位（Language And Woman's Place）](http://www.ngocn.net/news/2017-10-31-fbe0f036888d2ea9.html)
- [平权路漫漫：一场非赢不可的性别大战](http://www.ngocn.net/news/2017-10-23-1e6b0986801859d2.html)
- [性别薪酬差距的真相](https://www.bilibili.com/video/av16070914/)
- [父亲的生物学意义](https://www.bilibili.com/video/av1384059/?from=search&seid=6601234499716059192)
- [指责受害者It's your fault](https://www.bilibili.com/video/av6710522/)
- [父亲的生物学意义](https://www.bilibili.com/video/av1384059/?from=search&seid=6601234499716059192)

- [like a girl- do we limit girls](https://www.bilibili.com/video/av6122875/)

**Comment by alissli** [comment]
- [feminist.com](http://www.feminist.com)

**Comment by alissli** [comment]
- [宝贝X](https://www.bilibili.com/video/av17159016/)

**Comment by alissli** [comment]
### 微博账号

- [JoinFeminism字幕组](https://weibo.com/joinfeminismsubs?from=page_100505_profile&wvr=6&mod=bothfollow&refer_flag=1005050010_&is_all=1#_rnd1514613648990)
- [新媒体女性](https://weibo.com/u/1527379661?from=page_100505_profile&wvr=6&mod=bothfollow&refer_flag=1005050010_&is_all=1#_0)
- [膨胀工作室](https://weibo.com/u/6118161182)

**Comment by alissli** [comment]
### Remember hers
- [二战女程序员](https://www.bilibili.com/video/av10920305/）
- [玛格丽特 桑格](https://www.bilibili.com/video/av6735080/)
- [Edna St. Vincent Millay](https://en.wikipedia.org/wiki/Edna_St._Vincent_Millay)
- [speak out her name 1](https://www.bilibili.com/read/cv80016?from=articleDetail)
- [speak out her name 2](https://www.bilibili.com/read/cv107541?from=articleDetail)
- [speak out her name3](https://www.bilibili.com/read/cv116839)

**Comment by alissli** [comment]
### 术语

- [Gender](https://en.wikipedia.org/wiki/Gender)
- [Feminist psychology](https://en.wikipedia.org/wiki/Feminist_psychology)

**Comment by alissli** [comment]
### Videos
- [TED|Leila Hoteit: 3 lessons on success from an Arab businesswoman](https://www.ted.com/talks/leila_hoteit_3_lessons_on_success_from_an_arab_businesswoman#t-17864)
