### ISSUE TITLE
BP选题探讨

### ISSUE THREAD

**Issue by alissli** [alissli/MuLanStar#2]
### 初步想法

组员每人想一个生活故事，印象最深刻，或者最打动自己的。围绕这些故事雏形来选题。

**Comment by alissli** [comment]
##  观月亮猫编程有感

女孩到女人，女人再到母亲，三个世界，枷锁一层套上一层。

也许之前他们只是吓唬你，这个不能做，那个不能做。从女孩到女人，再到母亲，你发现不能做的不是少了，而是更多。

夜深人静，当你想坐下来敲一段代码，写一段文字，孩子哇哇哇得哭了。
有个重要的会议，孩子突然病了，是面对上司的责难请假，还是狠狠心把孩子交给粗心的爸爸、年老无力的老人？
再糟糕一些，假如孩子的爸爸是个隐形人呢？

再或者，
如果你选择了当全职妈妈
你能承受这24小时的全年无休吗？
你能坦然面对没有经济收入，仰人鼻息的生活吗？
或者，家人还能给你应有的尊重吗？

究竟是你不够强大，还是他们对你太【苛刻】？

我是一个妈妈
我希望有自己的事业，有个人的发展，为这世界更美好而做点什么，而不是仅仅养大一个、两个孩子。
我也希望孩子能健康的成长，受到必要的陪伴，受到良好的教育
我希望……
我希望有一条路，燃着的希望，不仅仅是，孩子终究会长大。

**Comment by alissli** [comment]
### BP设想

###  名字：她时代

- 背景：开智社团提倡向历史上的大牛学习，有次，一位女生在开智部落提问：历史上大部分大牛都是男性，由于时代的背景与原因，女性不可能复制男性的成功，那么这个时代的女性怎么办？

- 想法：一个面向女性的社团，提供信息服务，比如向寻求自我发展的女性提供像开智这样的时间源头的网络在线课堂，提供反性别刻板印象的女孩子兴趣爱好培训机构信息（比如月亮猫）；向职业女性提供职场歧视的法律咨询与援助，等等；单亲妈妈们的心理和生活支持信息；鼓励男性做两性关系中的合作者和共建者。

- 故事1: 「她」生活在一个更自由的时代，但还是有很多的性别偏见、以及障碍，让个人无法自由生长
- 故事2: 她遇到了「她时代」，她找到了自己的兴趣所在
- 故事3: 她帮助更多的「她」实现自我的价值

故事矛盾
- 她和丈夫吵架，妈妈劝她让步，「女人在外面再强，再光鲜，回家都是要做家务的」
- 她离开家，找闺蜜诉苦，闺蜜建议，对待男人要多夸奖，像对待小孩子一样
- 她很困惑，为什么小时候，男生与女生的要求是一样的，为什么长大就是两种标准了？
-……
- 共建一个性别平等的时代
- 做自己的人生导师

**Comment by alissli** [comment]
### 第一次讨论
- 171209 计划20:00～20:30，实际20:00～21:00

### 讨论复盘

#### 阶段1：起步

- Aliss建议第一次讨论以各自喜欢的一个故事入手，从故事中发掘BP主题。

- Helen提到BP就是解决人们的痛点，然后才能有商业价值。以父母陪孩子做作业入手，做一个APP：
  
> APP: 一棵开花的树（时间花在哪里哪里就开花） 
> 管理时间+习惯养成+成长心智 ()
> 栏目：
> 1. xxx
> 2. xxx
> 3. xxx
> ……
>
> 提到了「隐喻」：虫子在吃时间，我们要驱赶虫子，把时间利用好，不要在拖延和浪费中被虫子吃掉。并且提到了，「最好这棵树是真的在生长，都完成比较好的花，这棵树就长得枝叶茂盛，甚至开花结果」

- Mandy：作为幼教老师，发现1.5～6岁孩子的想象力、联想力和创作能力被扼杀了，希望讲一个帮孩子去发现生活之美，开启创作力的故事。如果能进一步去启发孩子发现自我，找到自己存在的意义就更好了。

- Aliss分析： Helen的思路还是沿袭了清单体，提议大家从最小故事模型入手,反过来想BP做什么。并且介绍了自己的故事模型。
> 我为什么会对性别平等这个话题感兴趣，是因为成立家庭以后，强烈感觉社会对两种性别的要求，有很大的差别。让我非常难以接受，并且时常怀疑自己。其实，这种怀疑，在之前也是有的，只是不知道为什么。后来接触了一些心理学，女权的思想，我明白有些并不是我自己的问题，那问题就渐渐变成，我如何在这个时代里寻找自己的定位？我想做些什么？
>
> 所以我写的那个故事模型，自己的色彩是比较重的。但这里面有些是共性的，我四期没有写，是因为没想清楚，到现在，还是没想特别清楚。今天下午的模型，也是受了一些阳老师故事+人性的启发，匆匆写的。
>
> 刚刚听两位讲的时候，我又有了点新的启发，我们可以自己的故事模型反过来检验这个点子是不是能成为讲好故事的BP。
>
> 现在就是按最小故事模型拆解一下，你不需要想清楚每一句话，利用快写慢改的方法，占位符就可以。

#### 阶段2：写故事

- Mandy

> 魔法糖果
A：民风保守的小镇上，一对旅居的母女初来乍到，开了一家糖果店，在朴素和拘谨的市民们眼里，母女穿着艳丽，和小镇格格不入，大家想要靠近这家店却不好意思。一位常年忍受家暴的妇女在心里悄悄被店里糖果的香味和温暖的色调吸引。
B：一天，这位家暴妇女偷偷进来，试图偷走一块糖果，母女俩发现却没有说破。第二天去家暴女家亲自送了一块糖果，家暴女吃了糖果，对美好生活的向往被唤醒了。
C：又是一天夜里，家暴女在丈夫打她的时候用平底锅回敬了丈夫一下，不顾邻居的劝说，离婚了。到糖果店里打工。从此，糖果店的客人越来越多，市民们逐渐敢于追求自己想要的幸福，不再拘谨了。

- Helen
> 故事1: 「她」是单位的骨干精英，她在商场上叱诧风云，她管理着一个有1000多人的企业集团，却因为无法陪孩子写作业而心生内疚，焦虑不安，“她”甚至为此不惜放弃自己的职业生涯，专职陪娃。
>
> 故事2: 有一天，她遇到了「一颗开花的树」，她找到到了她的救星和福星，在这里，有时间管理，有同侪压力，有答疑解惑，有互助小组，有亲子沟通，有情绪管理。不需要她在身边，只要孩子登陆APP，去完成各种闯关卡片，记录自己的成长，不断驱逐吞吃时间的虫子，这棵树就会一直长啊长。
> 
> 故事3: “一棵开花的树”帮助更多的“她”和“她”的孩子习惯养成和实现心智成长，慢养陪伴，静待花开。只要勤于驱虫，用汗水浇灌，顷刻之间，繁花盛开！

- Aliss : 为两位组员👏，12分钟内都写了个复杂故事出来。

### 小结

- Aliss：我的故事内核是「一个女性在当下时代的成长」。
> Helen第一个想法的故事版本可以这样拆解：
> 事件1: 父母陪孩子作业很烦恼
> 事件2: 发生了xxx
> 事件3: 父母陪孩子做作业很快乐／父母不用陪孩子做作业了 
> 
> Mandy的第一个版本：
> 事件1: 孩子天生的创造力被扼杀了
> 事件2: 发生了xxx
> 事件3: 孩子变得更有创造力和想象力

在新的版本里，Helen受到Aliss的故事影响，在孩子成长的主题里，揉进去了女性自我成长。而Mandy的故事里，核心主题是个人追求自我的幸福。

在看过Aliss的故事之后，Mandy又给出了如下故事：

> 1 她大龄未婚，但是自己努力工作活得很充实，不觉得失落
2 她身边的人催她笑她，她仍觉得自己的人生应该自己定义，可是现在的世界抛决然弃了她
3 她遇到了她世代，那里的她不管已婚未婚，都活出了自己想要的样子，找了母亲和女人这个身份以外的归宿

#### 总结

- 三个组员关注的共同点都包含有「成长」的话题，Helen更关注孩子的自律，Mandy关注个人自由和幸福，Aliss关注女性在部分受限的情景下的自我价值实现。

#### 下一步行动

- 研读4期优秀BP作业，确定最小故事模型
- 171210 21:00前完成第一稿项目公示

**Comment by alissli** [comment]
请队员@hellomandy和@doraemo2018对上面的复盘进行补充，直接回复本issue。另外，请在171210 17:00前在本issue下回答以下问题：
- 你最喜欢哪个作业？请说出至少一个打动你的点，或者你印象最深刻的点。

**Comment by hellomandy** [comment]
# 第一次线上讨论复盘：
## 头脑风暴阶段：
自己的准备特别不充分，会议前没有好好读issue仓库里的故事和文章，也没有准备好最小故事。讨论过程我像卖火柴的小女孩那样，擦亮火柴后还没看清楚眼前的世界，就只剩下一点思维的火星了。非常懊悔，时间不多，以后每次集体讨论我自己务必要做足准备。
##  现场快写最小故事：
我的最小故事[魔法糖果]脱胎于电影《浓情巧克力》，裁剪了一部分做为我讨论的最小故事。故事里用“糖果”做药引，治疗人们压抑自己，不敢追求幸福这个疾病。核心是想鼓励人们勇敢追求幸福。

helen的故事：[开花的树]明线：一个app，可以帮助孩子自觉快速写好作业，养成好习惯，孩子作业完成了，家长也开心了。暗线：时间是宝贵资源，会被虫子吃掉，也可以用来种树。用在种树上，那么这颗树就会开花结果，孩子也能看到生命被好好利用了。（此处我想到了支付宝里的蚂蚁森林，绿色消费可以增加能量，然后能量够了就可以在沙漠种一颗树）不过Helen设想的App意味更加深远，想法很好，学习了。个人认为想法如果要落地，如果能运用认知写作的知识去创造更新奇更性感的隐喻，孩子和家长实施的行动力会更强。

aliss的故事：[她世界]一个渴望独立，不甘被埋没的女性读起来一定是很有共鸣的，没错，说的就是我自己哈！aliss倾诉了一个身为母亲的女性在当代会遇到的各种不平等。我不能感同身受，但是同为女性，多少知道社会对女性这个角色的苛求。即兴补充了aliss的[她世界]一个未婚女性遇到的不平等。而无论已婚未婚，我在合并后的故事中解读到的女性困境是，在时间的无情的流逝中，在自我实现和演好社会角色和天赋使命之间的挣扎。

# 小结：
归纳一下三个人共同的关注点：时间  成长 追求意义和价值（自己的 孩子的 ）
目前我感受到的困难：
时间紧迫，还没有想好一个故事模型，而我个人的写作风格是容易假大空，不接地气，想好久写不出一个贴近生活的故事。四期Bp[月亮猫]是我比较欣赏的，目前还没有细看，但是成功之处在于很好地找到了一个落地点：女孩通过编程而与众不同。

# 讨论过后的想法:
受aliss，helen共同启发，本次Bp作业最好围绕女性的，或者孩子的价值实现来说故事，用时间这条暗线去体现故事的深度，现在欠缺的是行动者的强烈动机（要具体和自然），同时欠缺一个好的喻体。
















‘’

**Comment by Helenzwh** [comment]
# 第一次线上讨论复盘：


## 准备阶段：
个人准备不是很充分，优秀BP展示倒是抽了时间看了两个，但是对于最小故事，总觉得应该要好好构思，所以一直没有行动。几天在脑子里盘算的一直是和儿童发展成长相关的东西。我的第一个想法的灵感来源是前不久朋友圈疯传的陪孩子做作业家长的各种吐槽和焦虑，所以想做一个关于小学生时间管理和习惯养成的BP。另一想法是关注是青少年思维成长的方面，主要想做关于深度阅读方面，以读促写，但是因为没有找到一个比较好的切入点，遂作罢。
***
##写故事阶段：

*Aliss*
名字：她时代
背景：开智社团提倡向历史上的大牛学习，有次，一位女生在开智部落提问：历史上大部分大牛都是男性，由于时代的背景与原因，女性不可能复制男性的成功，那么这个时代的女性怎么办？
想法：一个面向女性的社团，提供信息服务，比如向寻求自我发展的女性提供像开智这样的时间源头的网络在线课堂，提供反性别刻板印象的女孩子兴趣爱好培训机构信息（比如月亮猫）；向职业女性提供职场歧视的法律咨询与援助，等等；单亲妈妈们的心理和生活支持信息；鼓励男性做两性关系中的合作者和共建者。
故事1: 「她」生活在一个更自由的时代，但还是有很多的性别偏见、以及障碍，让个人无法自由生长
故事2: 她遇到了「她时代」，她找到了自己的兴趣所在
故事3: 她帮助更多的「她」实现自我的价值

*Mandy*
魔法糖果
A：民风保守的小镇上，一对旅居的母女初来乍到，开了一家糖果店，在朴素和拘谨的市民们眼里，母女穿着艳丽，和小镇格格不入，大家想要靠近这家店却不好意思。一位常年忍受家暴的妇女在心里悄悄被店里糖果的香味和温暖的色调吸引。
B：一天，这位家暴妇女偷偷进来，试图偷走一块糖果，母女俩发现却没有说破。第二天去家暴女家亲自送了一块糖果，家暴女吃了糖果，对美好生活的向往被唤醒了。
C：又是一天夜里，家暴女在丈夫打她的时候用平底锅回敬了丈夫一下，不顾邻居的劝说，离婚了。到糖果店里打工。从此，糖果店的客人越来越多，市民们逐渐敢于追求自己想要的幸福，不再拘谨了。

*Helen*
主题：一棵开花的树（时间花在哪里，哪里就开花）
故事1: 「她」是单位的骨干精英，她在商场上叱诧风云，她管理着一个有1000多人的企业集团，却因为无法陪孩子写作业而心生内疚，焦虑不安，“她”甚至为此不惜放弃自己的职业生涯，专职陪娃。
故事2: 有一天，她遇到了「一颗开花的树」，她找到到了她的救星和福星，在这里，有时间管理，有同侪压力，有答疑解惑，有互助小组，有亲子沟通，有情绪管理。不需要她在身边，只要孩子登陆APP，去完成各种闯关卡片，记录自己的成长，不断驱逐吞吃时间的虫子，这棵树就会一直长啊长。
故事3: “一棵开花的树”帮助“她”的孩子习惯养成和实现心智成长，慢养陪伴，静待花开。只要勤于驱虫，用汗水浇灌，顷刻之间，繁花盛开！

这个故事是我在12分钟构思并写出来的，时间仓促，难免有漏洞和瑕疵，但是也是第一次在高压下完成了，不论如何，完成大于完美，特别感谢Aliss 和Alice，在他们的同侪压力和启发下，我完成了这次脑力激荡体操。个人认为，总体来说创意是好的，但是隐喻和切入点还需要打磨。看了Alice对我的想法总结得非常到位，讲出了故事的主旨，进一步帮我整理了自己的思维和故事，非常感谢。
>helen的故事：[开花的树]明线：一个app，可以帮助孩子自觉快速写好作业，养成好习惯，孩子作业完成了，家长也开心了。暗线：时间是宝贵资源，会被虫子吃掉，也可以用来种树。用在种树上，那么这颗树就会开花结果，孩子也能看到生命被好好利用了。（此处我想到了支付宝里的蚂蚁森林，绿色消费可以增加能量，然后能量够了就可以在沙漠种一颗树）
##小结：

Aliss和Mandy的故事都关注了女性的觉醒，呼吁女性解放思想，追求自身的价值和幸福。
[月亮猫的故]事也是让女倾听自己的内心声音，勇敢追求自己的理想，让女性学编程来打破或挣脱世俗的偏见和刻板印象。因此，我的建议是如果做这个主题，要有一个具体的可操作的客体，或是法律援助，或是心理咨询，或是女性创业扶持和孵化，最好选择一个点，个人愚见，BP的名字要和所提供的支持和服务相关，最好有比较好的喻体和模因。

 我个人比较喜欢优秀BP展示中的“老树新芽”，这是一个融入了爱和“老有所用”、“老有所乐”的故事，可操作性强，并且有人文关怀、亲情、温情。这个题目也起的好，喻体和模因都很棒。

**Comment by Helenzwh** [comment]
至于喜欢哪个故事，我当然喜欢自己的故事，哈哈。
>最打动我的点：从实用角度来讲：儿童是祖国的花朵，他们的时间管理和习惯养成关系到自己将来飞得多高，走得多远，也关乎到以后人生的幸福。只有掌控好时间，做时间的主人，才能掌控好自己的人生。人生的很多失败和时空都来自拖延和不自律。过自律的人生，打败拖延症，立即行动，学会目标管理，从而培养专注的品质，注重儿童的全面发展和成长思维。
>从教育角度来讲：教育是十年树木，百年树人；教育是慢养陪伴，静待花开。有的孩子可能是一棵铁树，但是终究也会开花，可能只是慢一点。在这里，孩子们可以通过不断种植自己的树木，打造自己繁华似锦的秘密花园。在这里，成长可以记录，成长可以见证，成长可以预见。
***
不过，做哪个我都没有意见，第一次做，主要是抱着学习的态度。如果选女性的主题，我也会配合做好的。不过，我也会找时间把自己的那个创意再当一次练习，把它做好。

**Comment by alissli** [comment]
### 20171210 目标：完成项目公示

- 确定项目名称
- 确定一个故事方向
- 自己的140字介绍

### 讨论

- Helen的时间管理问题，其实在认知课程中老阳有讲到时间的隐喻。虫子吃时间的隐喻，和「花时间」是差不多的。开智模因提倡的是习惯，个人觉得同样适合孩子，老实说，这个隐喻展开，复制开智的做法就好了。
- 我的观点是，孩子习惯的问题，根本在于家长和家庭的氛围。其实陪作业的这个事情，本来就是有问题的。而且还要看，针对什么年龄段的孩子。比如开智的爱贝睿的产品只针对0～6岁，不同年龄阶段的孩子的成长特点是不一样的。

- 关于三个人的共同点，同意两位的分析。看在共同点上面，能不能达成共识。

**Comment by hellomandy** [comment]
20171210 
# 一点看法：

- helen陪孩子写作业的想法起源于网上的段子，灵感起源是段子，而时事和段子，这是阳老师不推崇去追逐的。陪写作业事件对人性挖的不够彻底，不够源头，同为教育从业者，认为作业写得慢，或者成绩上一时的落后对生命质量的结果没有强烈的因果关系。
以上，个人认为：写作业和时间管理的故事模型，吸引力弱。直接点说，是写作业这件事选歪了。
如果一个Bp不能打动我自己，就更难打动读者的。

- 看helen故事的暗线，如果我分析的没错，写作业时明线，珍惜时间和生命是暗线，我觉得暗线是可以做文章的，我们的故事其实可以改写成赋予时间意义，如果想往儿童发展方向走，建议一起想想，转换切入点，我暂时没想到，但是大家可以一起头脑风暴；如果往女性成长方向走，我认为受众定为20—40岁这个年龄段比较好，这一时期几乎可以遇到一生大部分的困境了。

## 关于隐喻的选择，如果时间是本体，我考虑过以下喻体：
[沙漏] 
[电池 ] 
[火柴]
[夏天] 如果一生是80岁，20-40岁正好是夏天
[四分之一的时钟] 20—40岁是人生的四分之一
以上，觉得都没有新奇的动人的感觉。

然后。又从想名字入手，
[X立方] 隐喻人生是立体的，鼓励行动者去追求多面的完整的人生
[X迷宫] 帮助行动者理清困境
[XX 原点] 灵感来源于《环形废墟》，生命的原点可以随意设置。

**Comment by alissli** [comment]
### 20171210 开脑洞讨论

先记录了一下，@hellomandy @Helenzwh 两位可以补充～

- 参考《开智故事》的意向「火」，想到了「星」，索德格朗的花园里落满了「星星的碎片」，也可以取「星星之火」可以燎原之意。
- 「星花园」感觉有点不够大气，Mandy提到了「草原」，从「花园」到「草原」想到了，「策马奔腾的女孩子们」
- BetterName工具给了一个「星则天」，Mandy想到一个「木兰星」

**Comment by alissli** [comment]
### 洗澡洗出来的灵感

讲性别平等，从女性的角度去讲，很容易没新意。不如从一个男性的视角去讲。

某某男婚后生了了一个女宝宝，孩子一天天长大，一天回到家中，很不开心。他询问后，原来是老师不让xxx，因为她是女孩子。爸爸想起了自己小时候，初意识到性别要求的不同。xxx（第二次、第三次冲突），爸爸也很困惑，爸爸想要找答案，找到了「木兰星」。「木兰星」解决了爸爸的困惑，爸爸坚持以平等的原则鼓励和支持孩子xxx，并拉拢妻子参与「木兰星」共建。

**Comment by alissli** [comment]
# xxx的填空

- 行动事件：生活中不使用【你是女孩子，xxx】，【你是男孩子，xxx】
- 行动事件：妈妈忙编程，爸爸陪孩子
- 行动事件：....

**Comment by hellomandy** [comment]
本组的成员全是女生，考虑到可能有视角局限，队长首先提议招募一个蓝孩纸，我也有此意，同时非常期待男女合作的项目中能做出更全面有吸引力的内容，所以拟好一个招募帖，以下：

是你吗？苍莽现世里，发现这颗星，而今它尚是一片荒土

上古伏羲女娲携手开世造物，后有木兰替父征战沙场，创造美好，承受风雨，本来就是两个性别共同的信念；伊甸园里，亚当和夏娃同食禁果，为何饱受生育之苦的却是女性？妲己亡殷，西施沼吴，杨妃乱唐，历史言之凿凿地给女性套上枷锁；磕磕绊绊里，女性走到了今天。

你是雄性，从出生起，就被教育要征服世界，而征途中，也必然要背负比雌性更重的责任。加班的时候，你可曾牵挂客厅里望着时钟等待父亲的孩童?病了，累了的时候，可曾希望妻子和女伴也能替你撑住家中的一片天?

人类生而孤独，而这世界上不过两种性别，缺少一种就会失去对称与平衡， 你也许是她的父，她的夫，她的XXX。而你和他是生命这趟单行车上的旅伴，当你帮她撑起沉重的手臂， 拉起手来，你们能拥抱更大的宇宙,茫茫夜空中，木兰星是一颗召唤女性独立的星，发现这颗星的你，慧眼独具，过去，现在，未来，男和女一直共存，而女性的独立离不开男性的支持，如果你想加入我们，做木兰星上的第一批垦荒者。那么，飞船入口在此


2017.12.12 根据aliss的建议来改写如下：



是你吗？茫茫夜空中追寻一颗星，不能安寝，不愿放手。

撕开宇宙的洪荒，女娲和伏羲开世造物，生命之初的绚烂是两种性别共同谱写的，而星移斗转，祸水成为红颜的另一张面孔，妲己亡殷，西施沼吴，杨妃乱唐...（确实不太明白《圣经》中“逐出伊甸园”里的逻辑，不敢妄言，所以抗去亚当夏娃同食禁果的部分，统一使用中国神话和历史里的例子。）

当女儿问你，为什么我不能玩打仗的游戏？当儿子问你，为什么我不能玩过家家的游戏？当同事问你，升职了吗？当身边的女性被问起，生了吗？打算何时要二胎啊？差不多要回家陪孩子了吧？你心里手否有过疑问，为什么类繁衍到今天，生育依旧是女性的包袱，而事业仍然是男性的负累。（例子借鉴ted视频里父亲的分享，再举不出生动的例子了，希望有蓝童鞋能补充啊）

世界上有两种性别，但人类却拥有同一颗心——向外拓宽生命的外延，向内挖掘命运的深意。生命如水，你的血管里奔腾的是河水，江水，还是海水？现在你看到的这颗星，指着大海的方向，它的名字叫做——木兰星。这是一颗男女平等的星球，我们需要女性去挣脱看得见的枷锁，也需要男性来戳破看不见的谬论。如果你想加入我们，做木兰星上的第一批垦荒者。那么，登录星球的地址在此[木兰星]（(https://github.com/alissli/BPstory-writer005/issues)

---
@hellomandy 抱歉，又回头看了第一版，感觉把你带歪了，也把我自己带进去了【捂脸】。第一版胜在情感指数，细节上尝试做些修改如下：

是你吗？苍莽现世里，发现这颗星，而它尚是一片待人开拓的荒土。

上古伏羲女娲携手开世造物，后有木兰替父征战沙场。承受风雨，创造美好，本来就是两个性别共同的信念；而伊甸园里，亚当和夏娃同食禁果，饱受生育之苦的却是女性。妲己亡殷，西施沼吴，杨妃乱唐，历史言之凿凿地给女性套上枷锁；披枷带锁的女人呵，一走就是千年。而这枷锁，锁住了女身，更锁住了「她心」。

你是男人，从出生起，就被教育要征服世界，而征途中，必须背负起比女人更重的责任。加班的时候，你可更牵挂客厅里望着时钟等待父亲的孩童? 病了，累了的时候，可曾希望妻子、女伴替你撑住外面的一片天?

人类生而害怕孤独，个体聚集成群，相互搀扶，迈过茫茫进化路，幸运成为蓝色星球的主宰。而这世界上的两种性别，缺少一种就会失去对称与平衡， 你也许是她的父，她的夫，她的子。你和她们更是生命这趟单程车上的旅伴，你们挽起手臂，能拥抱更大的宇宙。

茫茫夜空中，木兰星是一颗召唤女性独立的星，一颗打造性别平等世界的星球。发现这颗星的你，慧眼独具，过去，现在，未来，你我一直相伴，女性的独立离不开男性的支持，如果你想加入我们，做木兰星上的第一批垦荒者。那么，飞船入口在此

**Comment by alissli** [comment]
@hellomandy  具体说说我的看法
> 伊甸园里，亚当和夏娃同食禁果，为何饱受生育之苦的却是女性？妲己亡殷，西施沼吴，杨妃乱唐，历史言之凿凿地给女性套上枷锁；磕磕绊绊里，女性走到了今天。

- 这段就是自评说的证据不足不够能说服人，如果是我写，可能会说自上帝惩罚两个人（逐出伊甸园，额外给夏娃加上生育的惩罚），不过，这段最好还是查查圣经和相关解读，以免逻辑推理有问题。后面组块的意思，推测是『红颜祸水』, 可以直接质疑此结论。

> 你是雄性，从出生起，就被教育要征服世界，而征途中，也必然要背负比雌性更重的责任。加班的时候，你可曾牵挂客厅里望着时钟等待父亲的孩童?病了，累了的时候，可曾希望妻子和女伴也能替你撑住家中的一片天?

- 这部分就是建议看看那些支持性别平等的男性视角，再改写下。

> 人类生而孤独，而这世界上不过两种性别，缺少一种就会失去对称与平衡， 你也许是她的父，她的夫，她的XXX。而你和他是生命这趟单行车上的旅伴，当你帮她撑起沉重的手臂， 拉起手来，你们能拥抱更大的宇宙,茫茫夜空中，木兰星是一颗召唤女性独立的星，发现这颗星的你，慧眼独具，过去，现在，未来，男和女一直共存，而女性的独立离不开男性的支持，如果你想加入我们，做木兰星上的第一批垦荒者。那么，飞船入口在此

- 这个组块，建议和项目简介中「对自由、对成长的渴望，是不分性别的」模因统一。开智部落跟其他社群，最不一样的地方，吸引异类。什么是异类？对社会规范的偏离；是修辞的人生意义，对零度的偏离。

**Comment by alissli** [comment]
`aliss`

是你吗？目光在茫茫夜空中追寻一颗星，不能安寝，不愿放手。

撕开宇宙的洪荒，女娲、伏羲开世造物，生命之初的绚烂由两个性别共同谱写。后有木兰替父征战沙场，女不输男；星移斗转，「祸水」是历史为「红颜」描画的固定妆容，妲己亡殷，西施沼吴，杨妃乱唐……告诫这一代又一代的子孙：女子，不可以……历史也从来不会单面示人，或许，你也注意到另一种声音：男子，你应该……

而你，是享受现代文明的幸运儿。直到，你成了家，养育了孩子。
有一天，女儿问你，为什么我不能玩打仗的游戏？
再有一次，儿子问你，为什么我不能喜欢粉色？
多年不见的前同事见面寒暄，第二句必定是高升了了吗？而你偶尔路过女同事的桌旁，围着她的问题，乏味得你根本不想停下脚步：结婚了吗？生了吗？打算何时要二胎啊？差不多要回家陪孩子了吧？

你是不是心里一直以为，这样的秩序，就是我们本来的模样？我和你，也曾一样。

直到有一天，我发现一段视频[]()，听到这么一段话：当一个黑人女人站在镜子面前，她想的是，「嘿，我是一个黑人女人！」当一个白人女人站在镜子面前，她想的是，「嘿，我是一个女人！」，而一个白人男人站在镜子面前，他想的是，「嘿，我是一个人！」。语言不是思想的外衣，语言是认知本身。



～看过生物学对性别的定义，你笑了。雌性之所以为雌，不过是因为生殖细胞个头大一点。聪明如你，被另一个念头击中，男和女，会不会又是人类大脑爱分类的偷懒？xxx～

**Comment by zhijinkai** [comment]
大家好！我叫至金，来自珠三角大区辛波丝卡战队。受 @alissli 私下邀请过来参加该作业项目的观察员^_^。希望BP作业圆满成功。🙏    
作为一名男青年，对女性、对女性美我个人总是饱含着深深的热爱。我曾经读过这样一句话：你可以在每个女人身上看到西施。从名家作品中、诗词中、心理学研究、还有女性主义哲学中我不只一次这样去被你们的女性的美所吸引。​​​​这个世界之所以美丽、是因为女性把这个世界装点得美。五光十色的时装、美丽的发饰....  
像 @hellomandy 说这个组全是女性、提议需要招募一个男性视角的小伙伴、怎么说，从某种意义上作为一名男性我想告诉你们、我是和你们站在一起的。喜欢alissli前文中说的这样一句话：**男性做两性关系中的合作者和共建者。**  阴性内核主要发生联结，阳性内核主要产生引领。没有谁强谁弱的说法、都是为角色平衡。当阴性不能在阳性这边得到引领时她就马上会展现阳性特征女强的一面。当阳性缺失阴性的补充时他同样会像孩子一样犯错。   
在接下来的项目观察中还请各位为我指明一些工作要义。因为我也是第一次参加BP作业、有很多东西还需要向各位学习。做得或说得不好的还请各位指正。通篇读下来感觉各位的故事都非常吸引我。谢谢大家

**Comment by alissli** [comment]
选题方向确定，本议题关闭
