### ISSUE TITLE
BP公示

### ISSUE THREAD

**Issue by alissli** [alissli/MuLanStar#3]
## Change Log
- 2017.12.09 建立
- 2017.12.10 初稿
- 2017.12.11 发布至课程仓库[结业项目公示issue](https://github.com/AIWriter/Writer005/issues/162)下

---
### 7w进展更新

- 打磨故事模型

故事或许是这样开始的：

「爸爸，今天在幼儿园，男孩子们玩冲锋枪，老师不让我玩！」。女儿撅着小嘴，气鼓鼓地向他抱怨。
他笑了笑，把女儿举过头顶，安慰道，「那你可以玩布娃娃呀？」
「我就是想玩枪，打仗的游戏太有意思了！」他愣了愣。
「东东今天也特别不开心，玩游戏的时候，他当爸爸，想给娃娃宝宝做衣服，被别的小朋友嘲笑了。」东东是女儿在幼儿园的好朋友，一个聪明的男孩子……

---
## 项目名称

**木兰星**（暂定）

### 项目概述

- 团队项目协作[仓库地址](https://github.com/alissli/BPstory-writer005/issues)

- 项目简介: 女性从女孩到女人再到母亲，比起地球上的另一类性别，路总是走的艰难一些。一百年前，伍尔夫就告知女性，如果想写作，你必须有一间自己的房间和五百磅的年金。那时候，牛津的校园还是不允许女性踏足的；再看看那些十九世纪末二十世纪初，有机会成为作家的女性们，有些过于巧合了，要么终身未婚，要么婚后无子女。一百年后，情况改观了吗？当然，女人们写作不再是稀罕事。可是其他呢？四期BP作业《月亮猫》讲述了一个想要学习编程的女孩的故事。你看，当新的事物诞生，女性仍然不首先被鼓励尝试。开智是一个极具极客气质的社群，阳老师常常感慨无论是部落还是课程，性别比总是趋于1:1。这是不是说明，对于自由的向往，对于成长的渴望，从来就没有什么性别差异的「传说」？但是，现实是时代进步了，环境更宽容，女性依然面临着实际的困境，不仅来自自身，仍然更多的来自社会。一位女性部落成员曾问，历史是「他的历史」，开智提倡追随大牛的脚步，作为女性，我们应该追随谁呢？这问题可以是，**在这个依然性别不平等的时代，作为女性，我们可以成为什么样的创造者呢？作为男性，我们又在其中扮演什么样的角色呢？**

- 项目执行计划
  - 6W组队
  - 6W打磨选题
  - 7W最小版本
  - 8W，9W集中BP
  - 10W路演

- 关键时间节点

  - ～6wd5（171208）项目提交～计划6wd7（171210）项目提交
  - 9wd5（171230）提交Demo
  - 10w路演（180101～180103）
  - 10wd5（180105）
  - 171221～171226 Helen请假

### 团队成员介绍

- 分工：aliss（组长）+ 弃疾战队 + alissli + [仓库链接](https://github.com/alissli/Writer005)
- 个人简介：一个正走在转行路上的大龄女青年，一个把育子当成自我成长磨砺的母亲，一个怀揣梦想的创造者。

- 分工：mandy（剪辑、美术） + 弃疾战队 + hellomandy + [仓库链接](https://github.com/hellomandy/Writer005)
- 个人简介：一个到处找风景，满世界挂相框的人，一个带着问号来这个世界的人，一个长大了的孩子。

- 分工：Helen （暂定）+ 弃疾战队 + Doraemo2018+ [仓库链接](https://github.com/Doraemo2018/Writer005) 

- 个人简介: 英语教师，一双儿女的妈妈，一个想用写作抵御孤独和治愈心灵的人。

- 分工：Daisy + 弃疾战队 + daisykd + [项目仓库](https://github.com/daisykd/Writer005) （因为前一阵准备心理学考试，落下四周课程，正在慢慢补上）

- 个人简介: 姐姐弟弟的妈妈，育儿育己、阅读写作学习，简书 & 微信公众号“心心的礼物”，和孩子一起成长。愿结交爱学习、爱读书的小伙伴一起成长。

- 观察员：@至金
	
### 当前招募需求：
- 组员
  - 目前4名。
- 观察员
   - 3～4名，
   - 期待特长 : 对项目感兴趣，想要提出各种宝贵意见的小伙伴们都欢迎，尤其欢迎男同胞～

**Comment by hellomandy** [comment]
### 团队成员介绍

- 分工：mandy + 弃疾战队 + hellomandy + [仓库链接](https://github.com/hellomandy/Writer005)
- 140字以内的个人简介：
一个到处找风景，满世界挂相框的人，一个带着问号来地球的人，一个长大了的孩子。

	
### 当前招募需求：

- 组员 
   - X 名
   - 期待角色以及特长
- 观察员
   - X 名
   - 期待特长

**Comment by Helenzwh** [comment]
分工：Helen + 弃疾战队 + Doraemo2018+ [项目仓库](https://github.com/Doraemo2018/Writer005) 

个人简介: 英语教师，一双儿女的妈妈，一个想用写作抵御孤独和治愈心灵的人。

**Comment by daisykd** [comment]
分工：Daisy + 弃疾战队 + daisykd + [项目仓库](https://github.com/daisykd/Writer005) （因为前一阵准备心理学考试，落下四周课程，正在慢慢补上）

个人简介: 姐姐弟弟的妈妈，育儿育己、阅读写作学习，简书 & 微信公众号“心心的礼物”，和孩子一起成长。愿结交爱学习、爱读书的小伙伴一起成长。
