### ISSUE TITLE
BPstory大爆发

### ISSUE THREAD

**Issue by hellomandy** [alissli/MuLanStar#4]
### 在这里，讲述你认为感触最深，最能打动人的BP故事，你就是我，我就是你，用我心，换天下心。

**Comment by hellomandy** [comment]
### 故事一 
5岁的小宝在某培训机构上课，下课的时候，妈妈不小心碰了一下小宝的积木作品，小宝大怒，冲妈妈吼道：“你看看你干了什么啊，真是一点用都没有。”妈妈在一旁隐忍不发，这一切，上课的女老师都看在心里。
又一次上课，模拟买东西，老师道：今天我们模拟买卖游戏，我扮成老板，你们要扮演成顾客来买东西哦。小宝：“老板娘好，请问XXX”“为什么叫我老板娘？"因为你是女的，爸爸说过，女人怎么可能当老板？"

课后，老师偷偷问小宝，在家里，爸爸对妈妈好吗？小宝歪着头天真地笑道，在家里我和爸爸可以随便吼妈妈，妈妈从来不反抗。

### 故事二
夜里12点，哄好生病的孩子，她去关窗，今天的星光很美，她不由地出了神，想起学生时代的自己，在失眠的夜里，常常像今夜这样，趴在窗台上看星星。她觉得宇宙很大，但星星很美，希望自己能在这一生里像星星一样，发出光辉照耀人间，度过无憾的一生。

两年前，她刚刚怀孕，当时她本来有机会竞争更好的职位，却在摇摆的心情中被丈夫和家人劝说着放弃了，两年一晃而过，她至今待在原来的岗位上，庸庸碌碌，拿着微薄的薪水。

又是一个失眠的夜里，她看到一个网站：首页是一段动画，黑漆漆的夜空里，星光隐隐闪烁，一段文字像水一样从屏幕背景上缓缓流出，流进她的心田，等涌出眼眶时，已经变成一串眼泪。
“每个人都是天上的一颗星，仰望星空时，你可曾记得，你的生命本身，也是灿烂的星辰？”
半年后，她已经成为网站上的活跃建设者，通过讲述和分享自己的故事改变了很多女性。这个网站帮助18-45岁的女性做身份定位和生涯规划，积极培养兴趣爱好，鼓励女性什么时候都不要放弃自己的追求，提醒女性在除了女儿，母亲，妻子之外，不要忘记最初始的身份）——一个完整的纯粹的人。这个网站上最耀眼的一个项目是男性参与的——[映客计划]（先这么叫吧）帮助自己的妻子成就事业的男人，可以在网站上点亮一颗星，成为年度映客的男性，可以XXX(暂时想不出来)

**Comment by alissli** [comment]
### 快写初版

一步、两步，漆红色的防盗门，一抬头就在眼前。刚刚会议室里的争论余音，在脑海里淡了下去。
「丁零当啷」，开门的声音刚落，一个粉色的小身影，扑了上来，「爸爸——」他下意识地弯腰去抱，女儿笑嘻嘻的小脸已经贴上来。妻子带着围裙，手捧着热气疼疼的汤，正往餐桌上放。回头嗔怪着女儿：「快点下来，爸爸工作了一天，多累啊！」

女儿不肯，还偎在怀里，小嘴撅的老高，「爸爸，今天幼儿园里玩游戏，我要和男孩子们一起玩打仗，老师却不让。」女儿顿了顿，「老师说，女孩子不能玩打仗，爸爸，这是为什么呀？」

他笑了笑，张嘴正打算回答，却愣住了。「为什么？」

今天在会议室里，Cindy咄咄逼人的样子又在脑海里浮现出来。潜意识里，他知道，Cindy的数据是没有问题的，可他就是觉得不舒服，不愿意承认。当时，他可能还有些愤恨，「一个女人，这么盛气凌人，也不怕嫁不出去！」

妻子已经端出了最后一盘菜，招呼父女俩快点洗手吃饭。

餐桌上XXXx，妻子温婉的眼神透着光。

妻子跟他是大学同学，本来也有一份很有前途的职业。婚后两人很快有了孩子，出于对孩子未来教育的考虑，妻子放弃了xxx，xxx。

刚开始，他觉得理所当然，但近几年他越来越觉得说不清楚的不安。

xxx

大学同学在运作一个「木兰星」的项目，发介绍问他意见。他注意到「性别平等」几个字。

「性别不平等吗？，我们男人在外面辛苦养家，够累的了，还要……」他不以为然地翻着老同学发过来的资料。

不平等事件1
不平等事件2
不平等事件3

他决定参与这个项目。

**Comment by alissli** [comment]
### 20171217日 会议

- 确定具体项目进度
  - 171220 故事第一稿
  - 171220 keynote制作分工
  - 171223 keynote初稿
  - 171220 更新项目进度

- 确定人性主线
  - 公平——》偏见
  - 创造性——》平庸（女性抛弃性别刻板印象，追求自身的发展）

- 搜集故事素材
  - 根据自身经验或者生活的素材
  - 搜集男性角度的素材

### 讨论

- Daisy故事中「男性60%的把握就会去做，女性要有100%的把握才去做」，对女孩的教育不鼓励冒险
- Helen的三个年龄段的女性抉择，性别刻板印象下的困境
- Aliss分享大学同学在生了女儿后，关注性别平等问题，主动承担家务，让女儿在生活中的点滴感受到男女应该是平等的。

**Comment by alissli** [comment]
### 转一个关注女性主义的同学

以前确实没注意，自我感觉没太歧视女性，身边也没感觉到太明显的男女不平等，后来自己在别的方面一定程度上养成了自省的习惯，发现其实很多时候社会环境和传统造成女性的劣势还是挺明显的，包括自己潜意识里也有觉得女人不去男人的心态。我朋友圈里明显强调和关注女权的可能就你一个，开始也没放在心上，这几年女儿稍微大点了，关心女儿的方方面面，由此也对你关注的这个问题经常思考。其实最大的动力想为女儿创造一个更加良好的社会氛围，起码从自己做起，让女儿骨子里就觉得男女是完全平等的，比如说在家里，多尊重老婆，多做点家务，都是一种熏陶，起码不会让女儿觉得这些小事就应该是她妈妈做的。

---
思考
- **自省**是否能在讲故事中唤起共鸣？

**Comment by daisykd** [comment]
**12/18 21:30~23:20 还是边写边改**
1.
心心四岁时就显示出小小花木兰的气概。爸妈期待心心抱着娃娃搂搂亲亲，心心爱在地板上开小汽车；爸妈期待心心安安静静，心心蹦蹦跳跳；爸妈期待女儿小鸟依人，心心常拿爸爸当沙袋，爱用小拳头锤锤爸爸的啤酒肚。

爸爸对此忧心忡忡。常常柔声叫心心：斯文点啦，说话小声点啦，女孩子要斯文点。

心心上中班时，我们给她报了一个芭蕾舞班，希望用艺术熏陶一下这位小小花木兰。心心喜欢跳舞。她跳舞时温柔可人，可是平日依旧风风火火。

心心爱动手制作，看着公众号视频自学，用白醋和小苏打做“火山喷发”，喷出的“岩浆”流了一桌子。有了小弟弟以后，心心更加释放天性，和弟弟一起把家里搅成一锅粥。

心心的小学有兴趣课。爸妈期待心心参加一个唱歌跳舞团，心心选了一个动手制作的兴趣班。一周一次作业。有一次的作业是自己动手接电线，点亮一个小灯泡。心心一个晚上就完成了作业，然后兴奋地向妈妈展示如何“短路”（这可不是作业要求）。她把金属夹子夹在裸电线上，一下冒出了火星，点亮的小灯泡一明一暗闪了几下。妈妈吓了一跳。

爸妈喜欢活泼的心心，可是也忧心忡忡，女儿要是再温柔一点、淑女一点就好啦。爱动手当然好，可是搞电路这么“接地气”的活儿，在爸妈的刻板印象里，这是蓝孩纸的活儿。爸妈期待的心心，是琴棋书画，贤良淑德。到底，是女孩纸嘛。

2.
随着弟弟的诞生和成长、随着妈妈学习了心理学，妈妈在不断思考，对姐姐弟弟的期望，是不是应该调整呢？

两岁的弟弟跌倒时，会嘤嘤哭泣，像小猫咪。爸爸说：蓝孩纸要坚强哦、蓝孩纸不能哭哦。姐姐小时候跌倒了，爸妈马上冲过去抱起来，看看哪里受伤了。

我想到心理学老师说：所以通常女性寿命比男性长。因为女性想哭就哭，眼泪可以排毒。男性大多被要求喜怒不形于色，情绪憋在心里，久了就变成病。

我们教育男孩勇敢、女孩斯文；我们给男孩买汽车、鼓励他探索，给女孩买娃娃，鼓励她温柔；我们期望男孩长大成就一番事业、期望女孩长大当一个好妈妈。

可是，这样的教育，对小朋友的成长有帮助吗？

回想自己一路走来、好好学习、毕业上班、结婚生子、又生子，朝九晚五、工作带娃，泯然众人矣。时常夜深人静，姐姐弟弟熟睡，是难得的自由时间，可以读书思考。自己的这条路对吗、好吗？曾经的梦想呢？还有什么梦想没有实现？姐姐弟弟的人生、还有什么新的可能性？我能为他们做些什么？总觉得身在局中，却没能参透那一层薄薄的雾。

在写作版准备结业作业，小组提到男女不平等、家庭和社会对男孩女孩从小不同的期待、提到“木兰星”的创意。才恍然意识到，其实，我也是身在此山中。

普遍的印象依旧是：男人负责赚钱养家；女人负责相夫教子，当然还要貌美如花。看看那些做到高管的女性，大多男子气十足，哪里还有女人的味道。

可是，时代变了。新的浪潮扑面而来。

前些年，Facebook CEO桑德伯格的《向前一步》鼓励了一代女性追求职业上的成功。各行各业的杰出女性们，她们在追求事业的同时，也很好地兼顾了家庭。更可贵的是，她们站出来，分享自己的故事，促进社会的改变。

促成这种改变的重要一环，是男性观念的改变。丈夫对妻子的支持、男性领导对女性下属的支持、职场文化对女性发展的支持。

社会在进步。这不是一个最好的时代，但是一个美好的时代。

3.
从自己做起，改变观念、改变自己、改变育儿的观念。

男孩纸受到挫折，也需要爸妈温柔安慰；女孩纸也要被鼓励勇敢坚强、坚持自己的热情。

心心最近几个月迷上了编程。她自己用电脑编程，完全自学。她编了“接苹果”，打弹珠的小游戏、火娃娃和小猫赛跑、还有公主换衣服、换场景。

以前，爸妈觉得编程是IT男的活儿。现在，很愿意支持心心通过编程锻炼思维、探索世界。

未来的世界，属于有梦想、有好奇心、能够有独立思考的人。妈妈希望心心不是一个乖乖的淑女，而是有自省去发现自己的热情、有勇气去追求自己的热爱。

这些天，心心学了“五步拳”，每天在家里练习，并步抱拳一、弓步冲拳二、弹踢冲拳三、马步驾打四、歇步盖冲拳五......爸爸和心心“对打”，测试心心的打拳水平。

妈妈也在努力学习、积极思考生活的意义。

只有自己的改变，才能让这个世界往好的方向发展。心心，妈妈和你一起，用新的眼光审视人生、审视这个世界。

***
**思考**
* 写完看了看，感觉很零碎。本来想写三段小故事了，1（初始状态）+2（事件/行动）+3（反转），可是边写边改，最后看起来，都是一句一句的句子。并不是三段小故事。哎。
* 想多花点笔墨写“木兰星”的，可是没想好具体说那些功能，又不想“推销味儿”太浓。所以只是带过了。
* 嗯~~~总体还是感觉偏“干”，口号较多，没有代入感、没有调动读者情绪。所以，“知道”是一回事、“做到”是另一回事。
* 先这样吧。我尽力了，队长。-_-|||

**Comment by alissli** [comment]
@daisykd 鼓掌~我们「木兰星」的故事素材越来越丰富了。

**Comment by alissli** [comment]
by @Doraemo2018


有一个遥远的星球，叫木兰星，她唯美典雅，有深蓝宁静的大海，红色热情的沙漠，有洁白晶莹的建筑。她闪耀着女性的光辉，充满着女性的力量。传说，从那个星球回来，你的梦境将从黑白变成彩色。

---
### **18岁**
我叫何晓丽，我从小喜欢看美丽的星空，我的理想是当一个天文学家。

别人都说，我是痴心梦想。

高考结束，要填志愿了。

“女孩子，就应该学学文科，找个稳定的工作”。爸爸说。

“学金融吧，就业前景好，适合女孩子”，妈妈说。

你从小就听爸爸妈妈的话，这一次，我也没有反驳。

可是，到了大学，我发现我非常不喜欢这个专业，我经常面对着枯燥的理论发呆。

如果说，梦想是一场旅行，那浩瀚星空是我穷尽一生也无法抵达的地方。

也许面对现实，才是我正确的路。

一天，我仰望星空，想要找到答案，突然，在灰暗的天际里，仿佛若有光，飘过一架闪着金属灰光泽的飞船，降落在我的身边。

在木兰星的一周里，我做了职业性格匹配测试，也做了职业生涯规划，木兰星的专家还给了大学学习生活规划的一些指导和建议。

从木兰星回来，我开始旁听天文学的课并着手准备考研。

三年以后，我如愿成为一名天文系的硕博研究生。

今后，我的征途将是浩瀚宇宙、星辰大海。

当然，我还要去拜访宇宙最美丽的那颗星-木兰星

如果，人只能活一次。那就让梦想照进现实，仰望星空，脚踏实地吧！



### **28岁**

你每天穿梭钢筋水泥的丛林里，把自己封闭在封闭的格子间里，你努力工作，业务能力突出，工作没两年，你被提拔为主管。

28岁生日的那天，因你的上司升调，公司提拔了一个各方面都不如你的男士。 

这个决定让所有的人大跌眼镜。

你不甘，你委屈，找公司领导理论。

“我们知道你很优秀，只因为你是女性，你要结婚生子，这将大大影响你对公司的贡献和投入程度，而我们需要的是一个能把事业作为重心的男性。”

”你们这是性别歧视！”你终于没有忍住自己，丢下一句掷地有声的话语，夺门而出。

夜幕降临，街道上是行色匆匆的归人，可是，哪里才是你的归途？你仰望天空。

突然，就在灰暗的天际里，仿佛若有光，飘过一架闪着金属灰光泽的飞船，降落在你的身边。
你在木兰星参加了“向前一步（leanin）”俱乐部，俱乐部定期组织交流活动，所有的职业女性和女性创业者聚在一起，分享经验，鼓励年轻的职业女性向前一步，提升自己的领导能力。

回来以后，你用出色的业绩和领导魅力征服了所有的同事和顶头上司，你如愿以偿地升职加薪。

你知道，那是木兰星的指引，使你挣脱无处不在的职场性别偏见枷锁，给了你“向前一步”的勇气。

**38岁**

你感觉在工作中很难体会到成就感，工作似乎变成了鸡肋，机械日复一日重复着自己，已经很久没有过心流体验。

回到家，是永远做不完的家务，孩子事无巨细需要你操心。父母年事已高，病房探望一段时间也成了你每日的课业。

你和另一半已经很久没有交流，因为和你同龄的他正处在事业打拼的关键期，把所有的时间和精力都献给了工作。

好不容易，你们能坐下来聊聊。你鼓起勇气，对他说，

“现在的工作和生活不是我想要的，我已经为这个家打拼了10几年，现在我想去实现自己的梦想。”

“梦想? 社会已经对35以上的人关闭了求职大门，何况女性？，还是把你的梦想基寄托在下一代吧。”揶揄中带着一丝讽刺。

你对妈妈说，“妈妈，我总觉得现在的生活缺点什么，我想做出去看看。”

“自古以来，女主内，男主外，家才是女人的归宿。”妈妈语重心长地说道。

你信步走出家门，天空晦暗阴郁，像一只无形的巨大的网，将你罩住，挣脱不得。你感到深深的窒息。
“难道我的天空要一直这样暗淡无光下去吗？难道这就是女性无法挣脱的宿命？”

你迷失在那里，辗转彷徨，找不到自己的方向。

突然，就在灰暗的天际里，仿佛若有光，飘过一架闪着金属灰光泽的飞船，降落在你的身边。

你在木兰星遇到了了千万和你一样境遇的女性，她们用自己的努力一步步实现了自己的梦想，你从那里受到了激励，你在那里倾诉自己职场中所遇到的困惑和问题并得到很好的建议和咨询，你在那里在职场中的女性要向前一步去克服外界的成见以及自我的束缚，摆脱内心的恐惧。

从木兰星归来，你仿佛换了一个人，充满了无穷的力量，你知道那是木兰星赐予给你的。。
你在木兰星窥见了未来的自己，你开始为实现自己的梦想而开始不遗余力地打拼。

你参加了开智作家部落，参加了开智认知写作课程。

你知道，自己未来会是一个写作者，一个创作者，是一个用文字影响和温暖这个世界万千女性的孤独旅人。

其实，你只是害怕。你怕你忘记自己的梦想，你怕一生都搁置了梦想。

可是这一次，因着木兰星赐予的巨大力量，你不再害怕不再彷徨。

下一秒你要打开心门，迎接属于自己的灿烂千阳。

### **尾声**
木兰星，一个充满女性力量，闪烁女性光辉的星球，穿透了时空，激励着万千女性，迎接属于她们的灿烂千阳。

**Comment by alissli** [comment]
### 前言

「木兰星」小组的伙伴们太棒了~~我们的MVP呼之欲出。

### MVP初想

- 简单故事一：何晓丽是两个孩子的妈妈，在和丈夫抚养一对儿女的过程中，意识到传统意识中对孩子刻板性别印象的塑造，萌发了创建「木兰星」的念头。
- 简单故事二：方教授从小长得偏女性化，遭受欺凌和嘲笑，成年后接触女性主义，成为大学教授，专门研究性别平等与教育。
- 简单故事三：38岁的安岚想要开创新的事业，遭遇家人不理解（女性应该相夫教子），上网寻求帮助，遇到木兰星，获知开智部落，参加写作课，找到了写作的意义。
- 复杂故事连接0： 何晓丽夫妇在寻找资料时，在互联网找到了方教授的信息，练习，了解到了「gender」社会性别的概念，我们每个人除了sex（生理性别），还有一个社会性别。为了普及性别平等的观念，打破二元对立的性别意识，组建了「木兰星」，安岚迷茫受挫时，在网上浏览，遇到了「木兰星」，她弄明白了社会性别对自己的束缚，获知开智学堂的信息，学习了写作课，更计划参加更多的课程，发掘人生更多的可能。

- 复杂故事连接1： 何晓丽夫妇在寻找资料时，在互联网找到了方教授的信息，练习，了解到了「gender」社会性别的概念，我们每个人除了sex（生理性别），还有一个社会性别。为了普及性别平等的观念，特别是对女性的束缚，组建了「木兰星」，安岚迷茫受挫时，在网上浏览，遇到了「木兰星」，她弄明白了社会性别对自己的束缚，获知开智学堂的信息，学习了写作课，更计划参加更多的课程，发掘人生更多的可能。

### 场景
- Mandy故事二中的仰望星空
- 下面这个场景也不错，是否可以加在38岁女性与「木兰星」相遇
> 又是一个失眠的夜里，她看到一个网站：首页是一段动画，黑漆漆的夜空里，星光隐隐闪烁，一段文字像水一样从屏幕背景上缓缓流出，流进她的心田，等涌出眼眶时，已经变成一串眼泪。
“每个人都是天上的一颗星，仰望星空时，你可曾记得，你的生命本身，也是灿烂的星辰？”

### 分析

- 参考[BP知识点运用](https://github.com/AIWriter/Writer005/wiki/HBPKnowledgePoint)故事套路，引入一个概念「社会性别」
- 故事主线人物3个，是否会略复杂？

**Comment by alissli** [comment]
### 任务
- 将故事分场景
- 搜集背景音乐
- 场景画面与人物形象：是否需要手绘？是否需要拍摄照片？
- 整合并剪辑

### 按故事分场景
1.  仰望星空，主人公何晓丽是全职在家的二宝妈妈，放弃职业感觉失落
2. 何晓丽陪伴孩子在公园里玩耍，女儿要和男孩子玩打仗，被旁边好心的爷爷阻止，说女孩子不应该玩这个。儿子想和女孩子们一起玩串项链，被其他妈妈们阻止，说是小姑娘玩的。（删除丈夫角色）
3. 何晓丽在网上搜索如何教育男孩子，如何教育女孩子，闯入方教授的个人主页。
4. 给方教授写email
5. 方教授回信
6. 方教授讲述自己的故事，小时候长的女性化，被人欺凌，性别刻板印象对人产生了压迫
7. 何晓丽知道了「社会性别」的概念
8. 何晓丽继续搜索互联网，发现性别二元对立的意识对很多人造成了伤害
9. 何晓丽做了一个app
7. 展示网站：「科普板块」、「信息咨询」和「故事讲述」
8. 安岚出场，身份介绍
9. 安岚与家人对话
10. 安岚郁闷离开家，掏出手机，无意翻到「木兰星」介绍
11. 读到「社会性别」与「故事」，搜索「信息」，发现写作课
12. 报名写作课，并联系了何晓莉
13. 安岚在结业大作业的项目中为「木兰星」做了小视频

### 8w安排
171221 12:00敲定故事的分场景（以时间为限算完成），先发MVP issue
171221 20:30确定任务分配
171223 20:00 整合

**Comment by alissli** [comment]
### 再分析

#### 故事的因果性不够，比如何晓丽为什么要做app？

- 何晓莉自身被社会性别身份束缚，她渴望成长
- 带孩子玩耍的偶然事件，引发她对一对子女的教育思考，然后寻找答案
- 方教授的出现解答了她的困惑，她对「社会性别」话题产生了兴趣
- 她继续搜索，发现了很多人被对立的男女二元性别身份所束缚，她想要做点什么

到上面因果线还比较自然，但为什么一定是app而不是别的呢？
- 尝试0: 方教授建议？
- 尝试1: 前面身份设定她辞职前，是个程序员，做app是否会自然一点？

#### 何晓莉的角色
- 主角，这个故事本身应包含她自身的成长
- 她通过建立「木兰星」，实现了人生意义

#### 方教授的角色

- 方教授的参与，一是二元对立性别对男性也有伤害，二是引入「社会性别」的概念以及对主流性别意识对人性压抑的提醒。

- 提问: 方教授的角色是否可以不需要？是否可以替换？
- 回答：可以替换成其他暗示比较专业的信息源。那么这里需要给方教授一个清晰的职业设定，xx大学的教授。

#### 安岚的角色

- 提问0：安岚的角色是否可以不出现？
- 回答：不太确定，安岚的角色暗含有「年龄歧视」的线索。
- 提问1：安岚的角色如果必须出现，还缺少什么？
- 回答：安岚的角色如果必须出现，就必须为故事的发展服务，现在的情节设计，可能是想说木兰星有帮助到别人。但这样就感觉自说自话。

### 思考

- 如果从「对立男女二元性别」对男生和女性的压迫角度，给出一个男生故事和女生故事，会比较有说服力。或者主线是女性束缚，暗线设定为对男性的束缚？

**Comment by hellomandy** [comment]
看完aliss的出版复杂故事，我的感受是：出现人物太多，线索跳来跳去。
aliss的自我分析很到位，我的建议是：合并人物，将安岚与方博士合并成一个男人，
我建议故事可以这样裁剪：
一，何晓丽是全职妈妈，曾经是一位设计师，在解决子女教育问题时闯入安岚博士的公众号，在性别平等问题上达成共识。
二，安岚博士是程序员，男性，但是受到性别束缚，用第二职业，一个育儿公众号的写手来派遣内心的痛苦，收到何晓丽的留言后两人决定创建[木兰星]
三，两人共同创建木兰星，何晓丽设计，安岚编程。
# 思考 
这样裁剪后，如果故事情节合理的话，我认为性别平等是明线，暗线是追求完整的人生，成为自己想成为的人。
目前，我认为何晓丽渴望自由和与所作为的心情可以引起读者的共鸣，但是安岚是男性，需要有一个有说服力的故事来讲述他的渴望。也就是需要一个合情合理的男性故事。

**Comment by alissli** [comment]
@hellomandy 
- 安岚写育儿公众号，那么也要给出合理的背景，比如他应该是有孩子的？
- 何晓丽和安岚博世为什么要创建木兰星，也需要一个合理的原因或者说设置一个情节去推进
- 需要再好好想想故事结尾的逆转怎么写，有一个写法就是Mandy的初版，呼吁同道参与「木兰星」建设

**Comment by alissli** [comment]
### 按故事分场景-版本2
1.  仰望星空，主人公何晓丽曾经是一名设计师 
2. 结婚生子后，放弃颇有前途的职业，在家带孩子
3. 她并不满足做全职妈妈，参加了在线的写作班，并关注孩子的教育
4. 女儿玩布娃娃，儿子玩飞机坦克的情景，引发了思考，她上网寻找答案
5. 何晓丽闯入方教授的公众号，被科普「社会性别」的概念
4. 给方教授写email
5. 方博士回信讲述自己的故事，小时候长的女性化，被人欺凌，性别刻板印象对人产生了压迫
6. 何晓丽继续搜索互联网，发现性别二元对立的意识对很多人造成了伤害，尤其是女性
7. 何晓丽在写作课上遇到了安岚
8. 安岚诉苦说自己想做新事业，不被家人支持（性别歧视和年龄歧视的混合，Mindset）
9. 何晓丽向安岚推荐了方博士的公众号，她们解决了很多困惑
10. 在准备结业作业的时候，她们萌生了做「木兰星」的念头
11. 两个月后，木兰星上线了。

### 思考与行动
- 再分析「老树新芽」和「开智世界」的结尾。
- 思考3的场景如何表现
-  6选取典型的事件，给出三个
- 8的展开要加入Mindset的概念
-  什么原因和事件更能推动10的发生？

**Comment by alissli** [comment]
### 性别歧视的隐喻
- 女性为物品：剩女、「你负责赚钱养家，我负责貌美如花。」、生育工具

### 聚焦
- 「木兰星」是要做成产品还是公益？
- 如果「木兰星」是产品，会？
- 如果「木兰星」是公益项目，会？

**Comment by alissli** [comment]
### 20171222思考
- 参考「开智部落」，下一步打磨按「每页每帧为基本单位表达」，以序号显示。
- 回顾小组故事素材，聚焦一个点。比如基于Daisy的故事更倾向于「性别平等环境中的儿童教育」，Mandy、Helen、包括aliss自己最初的设想都偏向于一个产品，如凋寒教练20171221点评提到的「女性成长、女性力量、女性援助」

**Comment by alissli** [comment]
[世界再大，大不过一盘番茄炒蛋](https://mp.weixin.qq.com/s/sqEL9jZAfqWcaedNEAK7vg)

- 由于是一个女孩，觉得自己不行。
- xxx
- 她做出了自己的作品

**Comment by alissli** [comment]
故事一

5岁的小宝在某培训机构上课，下课的时候，妈妈不小心碰了一下小宝的积木作品，小宝大怒，冲妈妈吼道：“你看看你干了什么啊，真是一点用都没有。”妈妈在一旁隐忍不发，这一切，上课的女老师都看在心里。

Daisy回家里问自己孩子，发现男孩与女孩的对未来的认识不同。

又一次上课，模拟买东西，老师道：今天我们模拟买卖游戏，我扮成老板，你们要扮演成顾客来买东西哦。小宝：“老板娘好，请问XXX”“为什么叫我老板娘？"因为你是女的，爸爸说过，女人怎么可能当老板？"

课后，老师偷偷问小宝，在家里，爸爸对妈妈好吗？小宝歪着头天真地笑道，在家里我和爸爸可以随便吼妈妈，妈妈从来不反抗。

你意识到了「性别不平等」你会做什么？

**Comment by alissli** [comment]
自问自答

- 促成你一次行动改变是什么？
- 足够的铺垫
- 做什么

**Comment by alissli** [comment]
### 歧视场景
- Mandy与孩子的对话
- 老公不满妻子忙自己的事情，不照顾孩子
- 小婴儿，会抱哥哥弟弟，不抱女儿
- 小A是优秀的女同事，一个人在杭州打拼。小A和M说，过两年我要回老家。M惊讶地问：为什么？经理说你做的很好，要提拔你做主管。
- 暑假参加小小工程师，男孩子多，老外的男老师，学院群照片，动手做作品。

### 平等场景
- 男士大声说出因为孩子请假
- 家庭主夫不再受到歧视
- 女的销售经理讲，男的补充一下

**Comment by alissli** [comment]
回到家，妈妈的电话来了，说跟爸爸又吵架了。
妈妈这些年一直忿忿不平，当年明明职业发展比爸爸更好，但是有年幼的我，和生病的奶奶，只好回家照顾家人。

**Comment by alissli** [comment]
### 20171223 Zoom会议

- 聚焦「木兰星」是帮助女性成长的星球

**Comment by alissli** [comment]
### 独儿子

- 两个姐姐，一个弟弟，弟弟是独儿子
- 给生了孩子的家庭写祝词，只有儿子可以写
- 生女儿叫「弄璋之喜」，生儿子叫「弄瓦之喜」
- 我是家里的男孩，将来要主事，家庭和家族的很多责任，我需要担当
- 「文化大革命」的经历，意识到「任何时候 不能 伤害 人的 尊严」
- 历史上的女性作为和亲的政治工具

**Comment by alissli** [comment]
### 方刚教授

- 不符合主流男性性别气质的男人，在社会性别的范式中，也同样是处于社会边缘的。青春期时被称为「娘娘腔」、「二尾子」、「娘炮」、「假男人」
- 反复说一件事，别人会说「你怎么这么婆婆妈妈，像个老娘们一样」
- 女人的性别气质被定义为「啰嗦的」、「不干脆的」，男性的气质是「理性的」、「决断的」，如果生理男人表现这种气质，会连女人都不如。
- 社会文化对男性的要求：阳刚的、支配的、主宰的。因为阳刚，男人必须不断追求事业成功；因为阳刚，男人被要求忽视健康；我是大男人，有点小病我不能去看医生。因为阳刚，男人有泪不轻弹；因为阳刚，男人必须在性上强大，「没有最好，只有更好」；因为阳刚，在人际关系上，男人永远扮演主宰的、支配的、被人尊重的角色。
- 女孩子从小被教育「外面很可怕」，不要一个人到没人的地方去，天黑很可怕，天黑就要赶紧回家。内心积累起这样的恐惧，长大了就可能不敢去空旷的地方。
