### ISSUE TITLE
卡片大法

### ISSUE THREAD

**Issue by alissli** [alissli/MuLanStar#7]
妈妈：对门的小沈，跟你年纪差不多，要么约着出来吃个饭？
女儿：妈，不要啦～
妈妈：那村口的段爷爷家的外孙，人挺忠厚老实，要不？
女儿：妈，说了不要啦。
妈妈：都看不上？要么上次和你从战场上一起回来的师将军，人长的帅，又读过诗书，看你们挺聊的来，也可以考虑考虑？
女儿：妈！

**Comment by alissli** [comment]
正月初六，木兰府张灯结彩，大门敞开，待迎送官书的命官。

一队排在门口的人群里，表姊扯扯木兰的衣角，悄声耳语，「昨天姑姑从你房里出来，不高兴呢。」
木兰皱了皱眉头，「唉，还不是说叫我早点嫁人。」
表姊捂着嘴，竭力压低了声音笑，「姑姑说的没错，毕竟女大当婚，男大当嫁。你出去征战这几年，也耽误了不少日子，在村里算老姑娘了！」
木兰不悦地皱了下眉头，瞪了姊姊一眼，她才作了声。

**Comment by hellomandy** [comment]
# 去不认识的大伯店里理发
理发店大伯：小姑娘挺可爱的啊，有对象没？
姑娘：没有
理发店大伯：要不要我给你介绍一个？
姑娘：不用了，谢谢啊。
理发店大伯：怎么能不要啊，我跟你说，我有个亲戚的儿子，27岁，长得很帅的。
姑娘：不需要，我想先好好工作啊（理发结束，拔腿就撤）

# 国庆长假结束，刚回单位
隔壁桌的大姐：假期回家了吗?
我：没有啊，没买到票。
大姐：怎么没票，我去看亲戚都买到票了
我:啊，你亲戚？
大姐：（嘴角一勾）就是我跟你提到的那个亲戚，跟你同乡，35岁，家里条件很好的，就是没对象。
我:（心里暗笑，上次你说要介绍对象我已经拒绝了啊，看来是拒绝得不够干脆啊）

**Comment by alissli** [comment]
父亲在台子上敲着烟袋，不吭声，堂屋的空气有点沉闷。母亲低声啜泣：我们这是为了你好，你出去征战这些年，虽然现在看着荣耀，背地里，不知道多少乡亲，都耻笑我们家。说一个女孩子，在外风餐露宿，和一帮男人天天混在一起，说不定早……」母亲的面容更加悲切，「早些寻个人家，也是替你正名啊！」

木兰求救地看着父亲，父亲佯装烟袋又灭了，没有正视她的眼睛。

回到房间，木兰心愤难平。「当年为爹爹免受军役之苦，今日却一句多的话，也不曾替我讲，婚嫁就是女子无法逃脱的命运吗？！」窗棱旁挂得那把xx刀，冷得刺眼。

**Comment by hellomandy** [comment]
村外的山坡上，木兰呆呆地望着天，打从战场回来，村里的人总是见面就问，将来打算怎么办？想嫁给哪户人家，木兰听着心烦。在军中驰骋那么多年，木兰早已退去了少女的仅有的一点怯懦，对父母之命，媒妁之言根本听不进去。
对面远远走来一个男人的身影，近了一看，是他！木兰还是小女孩的时候，曾经喜欢过的一个同村大哥哥。如今大哥哥已经娶了邻村的平凡妇人，孩子也都7岁了。古兰征战归来的事情他也是知道的，可是如今，他看着木兰的眼神里却有一丝同情，同情她空耗了最美丽的年华，至今没有嫁人，木兰看着他近了又远了，心中一片冰凉。

**Comment by alissli** [comment]
掀开厚重的粗兰布帘子，阳光裹着跳跃的灰尘，在右厢房里乱舞。这画面和儿时几乎没啥变化。木兰的心，轻松多了。十二年不见，奶奶抵不过这岁月雕琢，苍老了很多。木兰在耳边大声唤了几句，奶奶才扭过头来，浑浊的眼神里透出几分光亮：兰兰啊，你可回来了。奶奶这些年，每天都按时烧香拜菩萨，保佑你平安，更保佑你能和如意郎君一起归来。

木兰微微红了脸，「奶奶，我是保家卫国，杀敌陷阵，哪有心情儿女情长呢？」
奶奶如枯木般的手，轻轻抚摸着木兰搭在她膝盖的双手，「傻孩子，我们女人，生来的使命就是相夫教子啊，当年你执意要替父从征，说走就走了，奶奶气得要打你父亲，哪能让女孩子做男人的事呢。」
「奶奶！您看，我这不是也做得挺好吗？」
「好不好不重要，女人就不该去战场杀敌……」可能是说的久了，奶奶拼着气力挤出这些话
木兰噤了声，不再说话。

**Comment by hellomandy** [comment]
这几日，多年不曾热闹过的家里熙熙攘攘，老旧的门槛几乎被踏穿了。来者百分之八十都是说媒的媒人，生而为人，谁不曾对爱情和家庭有过热烈的渴望，过去十二年忙着打仗，顾不上，回到家里的木兰对婚姻也竟有了一点期待。可是，媒人们介绍的对象却让木兰寒了心。对象一，东村的大伯瘸了腿，之前的老婆死于饥荒。对象二，西村的大爷，年龄和父亲差不多了，性情古怪，据说动不动就砸东西打人，家里没有一样完好的桌椅。对象三，北村的傻子，小时候烧坏了脑子，一天到晚流口水。
木兰对媒人道，您介绍的对象没有正常一点的吗？媒人噗嗤笑道，木兰啊，虽然你也有几分姿色，但是你这岁数还没嫁，也算是全村的奇观了。再说了，在军中那么多年，你早已不是完璧之身了吧？
