### ISSUE TITLE
微信公众号「木兰星」素材

### ISSUE THREAD

**Issue by alissli** [alissli/MuLanStar#8]

**Comment by alissli** [comment]
### 功能介绍

**Comment by alissli** [comment]
### 公众号简介

### 公众号头像

### 公众号进入画面

**Comment by alissli** [comment]
### 公众号进入画面

**Comment by alissli** [comment]
### 公众号栏目

#### 栏目一：专栏
- 名人墙
  - 英国第一代程序媛Ted演讲：为什么有事业心的女人头是平的
  - 她历史|中国近代第一位女教授
  - 她历史|世界上第一位获得诺贝尔文学奖的女性
- 她说
  - xxx
  - xxx
  - xxx
- 他说
  - 男幼教老师的自由平等之梦
  - 一个男人的解构与重建
  - 一位爸爸的性别平等觉醒
#### 栏目二：探索
- 教育咨询
- 互助小组

#### 栏目三：木兰星
- 简介
- 加入我们
- 投稿专线

**Comment by alissli** [comment]
![adee2c4264c3bde1215a83640650bf50474e78d025b6d-0glsry_fw658](https://user-images.githubusercontent.com/23351109/34361411-d2bd185c-eaa4-11e7-9777-720d531b2258.jpg)
![planet-2078507_960_720](https://user-images.githubusercontent.com/23351109/34361412-d2f3caf0-eaa4-11e7-8b08-f5c8f0c9d64e.jpg)
![public-domain-images-archive-free-stock-photos-4-1000x666](https://user-images.githubusercontent.com/23351109/34361413-d32ca50a-eaa4-11e7-9c05-61ccae45c840.jpg)
![public-domain-images-archive-high-quality-resolution-free-download-splitshire-0002-1000x666](https://user-images.githubusercontent.com/23351109/34361414-d36aee0a-eaa4-11e7-9d14-6edba5287413.jpg)
![public-domain-images-free-stock-photos-004-1000x667](https://user-images.githubusercontent.com/23351109/34361415-d3a00b1c-eaa4-11e7-9324-1eac37a2b5e2.jpg)
![public-domain-images-free-stock-photos-architecture-attraction-italian-1000x580](https://user-images.githubusercontent.com/23351109/34361416-d3d4e49a-eaa4-11e7-99d1-073d346e1cf6.jpeg)
![Uploading public-domain-images-free-stock-photos-black-white-vintage-suitcase-girl-railroadtracks-walking-1.jpg…]()
![public-domain-images-free-stock-photos-girl-boots-standing-green-grass-field-1000x666](https://user-images.githubusercontent.com/23351109/34361418-d45018ae-eaa4-11e7-8336-9b40dc231977.jpg)
![public-domain-images-free-stock-photos-girl-tutu-pink-orange-turquoise-rings-hands-1000x666](https://user-images.githubusercontent.com/23351109/34361419-d483802c-eaa4-11e7-97e0-f5dd6465f235.jpg)
![public-domain-images-free-stock-photos-high-quality-resolution-downloads-nashville-tennessee-32-1000x666](https://user-images.githubusercontent.com/23351109/34361420-d4b6d9a4-eaa4-11e7-98f3-52267cfdbf09.jpg)
![public-domain-images-free-stock-photos-high-quality-resolution-downloads-public-domain-archive-1-1000x667](https://user-images.githubusercontent.com/23351109/34361421-d4ebd898-eaa4-11e7-9bcc-6e1ab9a44daf.jpg)
![public-domain-images-free-stock-photos-high-quality-resolution-downloads-public-domain-archive-5-1000x667](https://user-images.githubusercontent.com/23351109/34361422-d5210360-eaa4-11e7-8a97-6475182ecf47.jpg)
![public-domain-images-free-stock-photos-little-girl-child-reading-book-bedtime-nap-11-1000x666](https://user-images.githubusercontent.com/23351109/34361423-d553c304-eaa4-11e7-908d-dd393ed8ae8a.jpg)
![Uploading public-domain-images-free-stock-photos-porcelain-figure-vintage-british-17thcentury-style-1-1000x666.jpg…]()
![Uploading public-domain-images-free-stock-photos-wedding-dress-outdoors-green-grass-wisteria-vines-1000x666.jpg…]()
![Uploading public-domain-images-free-stock-photos004-1000x667.jpg…]()

**Comment by alissli** [comment]
![public-domain-images-free-stock-photos-porcelain-figure-vintage-british-17thcentury-style-1-1000x666](https://user-images.githubusercontent.com/23351109/34361453-356f2652-eaa5-11e7-80d5-e3227a49be8e.jpg)

![public-domain-images-free-stock-photos004-1000x667](https://user-images.githubusercontent.com/23351109/34361464-41dcaa5e-eaa5-11e7-9388-6f8ea120381f.jpg)
![public-domain-images-free-stock-photos-wedding-dress-outdoors-green-grass-wisteria-vines-1000x666](https://user-images.githubusercontent.com/23351109/34361467-4ad4d3d4-eaa5-11e7-8aaa-d82f5f22cacb.jpg)

**Comment by hellomandy** [comment]
![my-daughter-1440088](https://user-images.githubusercontent.com/32700221/34372222-3bcff6fc-eb0e-11e7-9477-298791af8b76.jpg)
![mother-son-1546365](https://user-images.githubusercontent.com/32700221/34372223-3d087544-eb0e-11e7-9c33-ff0a05449611.jpg)
![pregnant-1435168](https://user-images.githubusercontent.com/32700221/34372225-3de52ffc-eb0e-11e7-8990-13bb22274a4b.jpg)
![hands-1509113](https://user-images.githubusercontent.com/32700221/34372228-403eb048-eb0e-11e7-95ac-d411e8cddf28.jpg)
![father-and-daughter-2-1435445](https://user-images.githubusercontent.com/32700221/34372263-6fa6584a-eb0e-11e7-8f69-65c0e630beb9.jpg)

**Comment by hellomandy** [comment]
![clothespins-1417161](https://user-images.githubusercontent.com/32700221/34372283-92320f62-eb0e-11e7-85e2-7d876ca55b10.jpg)
![holding-hands-1317094](https://user-images.githubusercontent.com/32700221/34372288-a009af3c-eb0e-11e7-88ca-3b804975d444.jpg)
![mop-1431230](https://user-images.githubusercontent.com/32700221/34372294-a99f5628-eb0e-11e7-9331-a2d3d763d131.jpg)

![mop-1431228](https://user-images.githubusercontent.com/32700221/34372293-a5fb4662-eb0e-11e7-883b-481134e58145.jpg)

**Comment by alissli** [comment]
@hellomandy  参考下面链接中 **3. 配色**

[BP 实操指南](https://github.com/AIWriter/Writer005/wiki/HBPractice)
[adobe color](https://color.adobe.com/zh/explore/?filter=most-popular&time=month)
